mockname: "Mock{{.InterfaceName}}"
dir: gen/mocks
outpkg: mocks
with-expecter: true
packages:
  short_url/internal/repository:
    interfaces:
      IStorage:
  short_url/internal/repository/filestorage:
    interfaces:
      ILinkStorage:
